### ISSUE TITLE
7.1 will not start

### ISSUE THREAD

**Issue by tmpkn** [zhicwu/docker-biserver-ce#43]
Regardless which method I choose (build / compose / use your image), I get the same error when trying to start the container:

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
*** Running ./docker-entrypoint.sh...
*** ./docker-entrypoint.sh exited with status 0.
*** Shutting down runit daemon (PID 9)...
*** Killing all processes...

**Comment by tmpkn** [comment]
UPDATE: Looks like you need to uncomment last line in Dockerfile: CMD ["biserver"], otherwise docker-entrypoint does nothing (last if).

UPDATE 2: Looks like you're simply missing "biserver" in your 7.1 commands both here and on docker hub.

**Comment by zhicwu** [comment]
Sorry about that. Just ucomment the line and is now rebuilding 7.1 image.

**Comment by tmpkn** [comment]
The command bug is fixed, but it now crashes during pentaho startup:

08:34:22,671 INFO  [PeriodicStatusLogger] Caution, the system is initializing. Do not shut down or restart the system at this time.
Killed
*** ./docker-entrypoint.sh exited with status 137.
*** Shutting down runit daemon (PID 9)...
*** Killing all processes...
➜  docker-biserver-ce git:(7.1) ✗ 

I'll keep debugging and let you know if I find out the cause.

**UPDATE:** I've bumped up docker RAM from 4GB to 8GB and it seems to be working now, thank you for your help!

Version 17.09.0-ce-mac35 (19611)

**Comment by zhicwu** [comment]
Thanks @tmpkn. There's bad assumptions at:
- https://github.com/zhicwu/docker-biserver-ce/blob/7.1/docker-entrypoint.sh#L6
- https://github.com/zhicwu/docker-biserver-ce/blob/7.1/.env#L5

I'll test if 1GB or so is enough, remove/update JVM args and update readme accordingly.
